// @ts-check
// Since preact doesn't support @ant-design/icons we need to export them manually

import icons from "@ant-design/icons";
import fs from "fs/promises";

(async function main() {
	const outPath = "./src/assets/icons.ts";

	let codeImports = "";
	let codeExports = "";

	for (const name in icons) {
		if (
			[
				"default",
				"getTwoToneColor",
				"setTwoToneColor",
				"createFromIconfontCN",
				"IconProvider",
			].includes(name)
		)
			continue;
		codeImports += `\n${name} as Original${name},`;

		codeExports += `export const ${name} = createFactory(Original${name});\n`;
	}

	let code = `// Generated by tools/generateIcons.js
  
import { createFactory } from "preact/compat";
import {
  ${codeImports}
} from "../../node_modules/@ant-design/icons/lib/index";

export {
	default,
	getTwoToneColor,
	setTwoToneColor,
	createFromIconfontCN,
	IconProvider,
} from "../../node_modules/@ant-design/icons/lib/index";

${codeExports}`;

	await fs.writeFile(outPath, code, "utf-8");
})();
